cmake_minimum_required(VERSION 3.25.1)
project(ptr VERSION 1.0)
option(Cat "UES Cat?" on)
if(Cat)
    add_subdirectory(Cat)
    LIST(APPEND ptr_LIBS Cat)
    LIST(APPEND INCLUDE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/Cat")
    configure_file(${CMAKE_CURRENT_SOURCE_DIR}/Cat/cat_cmake.h.in cat_cmake.h)
    message(STATUS "ptr_LIBS = ${ptr_LIBS}")
endif()
LIST(APPEND INCLUDE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/include")
message(STATUS "INCLUDE_PATH = ${INCLUDE_PATH}")
file(GLOB SRC_PATH "${CMAKE_CURRENT_SOURCE_DIR}/src/*.cpp")
message(STATUS "SRC_PATH = ${SRC_PATH}")
add_executable(ptr ${SRC_PATH})
target_include_directories(ptr PRIVATE ${INCLUDE_PATH} ${PROJECT_BINARY_DIR})
target_link_libraries(ptr PRIVATE ${ptr_LIBS})
