cmake_minimum_required(VERSION 3.25.1)
project(tutorial VERSION 1.1)
option(USE_MYMATH "Use my math?" ON)
if(USE_MYMATH)
add_subdirectory(MathFunctions)
list(APPEND EXTRA_LIBS MathFunctions)
# list(APPEND EXTRA_INCLUDES "${PROJECT_SOURCE_DIR}/MathFunctions")
endif()
add_executable(tutorial tutorial.cxx)
target_link_libraries(tutorial ${EXTRA_LIBS})
message(STATUS "${tutorial_VERSION_MAJOR}")
message(STATUS "${tutorial_VERSION_MINOR}")
message(STATUS "${PROJECT_BINARY_DIR}")
message(STATUS ${EXTRA_INCLUDES})
# 添加子文件夹
configure_file(TutorialConfig.h.in TutorialConfig.h)
target_include_directories(tutorial PUBLIC "${PROJECT_BINARY_DIR}" )
message(STATUS "这里!${PROJECT_BINARY_DIR}")
message(STATUS USE_MYMATH = ${USE_MYMATH}) 